/*
 * File: app/view/BandDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iTenants.view.BandDetail', {
    extend: 'Ext.Container',
    xtype : 'bandDetail',
    
    requires : ['Ext.Img'],
    config: {
    	autoDestroy: false,
        itemId: 'bandDetail',
        scrollable: {
            directionLock: true,
            direction: 'vertical'
        },
        items: [
			{
			    xtype: 'toolbar',
			    docked: 'top',
			    title: 'Detail',
			    items: [
			        {
			            xtype: 'button',
			            itemId: 'backButton',
			            ui: 'back',
			            text: 'Krautrock',
					    handler : function(e){
					    	mainCtr.popToPrev();
					    }
			        }
			    ]
			}
        ],
        listeners: [
            {
                fn: 'onBandImageLoad',
                event: 'load',
                delegate: '#bandImage'
            }
        ]
    },

    onBandImageLoad: function(image, e, eOpts) {
        image.show();
    }

});