/*
 * File: app/view/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iTenants.view.BandIndex', {
    extend: 'Ext.Container',
    xtype : 'bandIndex',
    requires: [
        'iTenants.view.BandList'
    ],

    config: {
    	autoDestroy: false,
        itemId: 'bandIndex',
        layout: {
            type: 'card'
        },
        items: [
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Krautrock',
                items: [
                    {
                        xtype: 'button',
                        hideAnimation: 'fadeOut',
                        itemId: 'backButton',
                        showAnimation: {
                            type: 'slide',
                            direction: 'right'
                        },
                        ui: 'back',
                        text: 'Krautrock',
                        handler : function(e){
                        	mainCtr.popToPrev();
                        }
                    }
                ]
            }
//            {
//                xtype: 'bandlist'
//            }
        ],
        listeners: [
            {
                fn: 'onBackButtonTap',
                event: 'tap',
                delegate: '#backButton'
            },
            {
            	painted : function(){
            		Ext.Msg.alert('painted');
            	}
            }
        ]
    }
});