/*
 * File: app/view/BandList.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('iTenants.view.BandList', {
  extend: 'Ext.dataview.List',
  xtype: 'bandList',
  alias: 'widget.bandlist',

  requires: ['Ext.field.Search', 'Ext.plugin.ListPaging', 'Ext.plugin.PullRefresh'],

  config: {
    itemId: 'bandList',
    useSimpleItems: true,
    variableHeights: true,
    infinite: true,
    disableSelection: true,
    allowDeselect: false,
    scrollToTopOnRefresh: false,

    cls: 'bandListCls',
    loadingText: false,
    store: 'Bands',
    scrollable: {
      directionLock: true,
      direction: 'vertical'
    },
    items: [{
      xtype: 'searchfield',
      scrollDock: 'top'
    }],
    itemTpl: [
      '<div class="bandContent">{Name}</div>',
      '<div class="bandDelImgDiv" style="display: none;">',
      '<img class="bandDelImg" src="resources/images/return_icon.png" />',
      '</div>',
    ],
    plugins: [{
      xclass: 'Ext.plugin.PullRefresh',
      locales: {
        loadingText: 'pullRefresh.loadingText',
        lastUpdatedText: 'pullRefresh.lastUpdatedText',
        pullRefreshText: 'pullRefresh.pullRefreshText',
        releaseRefreshText: 'pullRefresh.releaseRefreshText'
      }
    }, {
      xclass: 'Ext.plugin.ListPaging',
      autoPaging: false,
      locales: {
        loadMoreText: 'listPaging.loadMoreText',
        noMoreRecordsText: 'listPaging.noMoreRecordsText'
      }
    }],
    listeners: {
      itemswipe: function(component, index, target, record, e, eOpts) {
        mainCtr.listSwipeDelFn(component, index, e, "BandIndex");
      }
    }
  }
});